CREATE TABLE "orders" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "status" BIGINT NOT NULL,
    "tracking_id" TEXT,
    "customer_id" BIGINT NOT NULL,
    "shipping_method_id" BIGINT NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_orders_by_customer_id" ON "orders" ("customer_id");
CREATE INDEX "index_orders_by_shipping_method_id" ON "orders" ("shipping_method_id");
CREATE TABLE "order_products" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "order_id" BIGINT NOT NULL,
    "product_id" BIGINT NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_order_products_by_order_id" ON "order_products" ("order_id");
CREATE INDEX "index_order_products_by_product_id" ON "order_products" ("product_id");
CREATE TABLE "products" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "stripe_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "stock" BIGINT NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_products_by_stripe_id" ON "products" ("stripe_id");
CREATE TABLE "shipping_methods" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "stripe_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_shipping_methods_by_stripe_id" ON "shipping_methods" ("stripe_id");
CREATE TABLE "customers" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_customers_by_email" ON "customers" ("email");
