version = 1

[[migrations]]
id = 5884353104082720069
name = "0000_migration.sql"
snapshot_name = "0000_snapshot.toml"

[[migrations]]
id = 4667527263618255349
name = "0001_migration.sql"
snapshot_name = "0001_snapshot.toml"
