version = 1

[schema]

[[schema.tables]]
id = 0
name = "products"
primary_key = { columns = [{ table = 0, index = 0 }], index = { table = 0, index = 0 } }

[[schema.tables.columns]]
id = { table = 0, index = 0 }
name = "id"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 0, index = 1 }
name = "stripe_id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 2 }
name = "name"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 3 }
name = "stock"
ty = "U32"
storage_ty = { UnsignedInteger = 4 }

[[schema.tables.indices]]
id = { table = 0, index = 0 }
name = "index_products_by_id"
on = 0
columns = [{ column = { table = 0, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 0, index = 1 }
name = "index_products_by_stripe_id"
on = 0
columns = [{ column = { table = 0, index = 1 }, op = "Eq", scope = "Partition" }]
unique = true

[[schema.tables]]
id = 1
name = "shipping_methods"
primary_key = { columns = [{ table = 1, index = 0 }], index = { table = 1, index = 0 } }

[[schema.tables.columns]]
id = { table = 1, index = 0 }
name = "id"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 1, index = 1 }
name = "stripe_id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 2 }
name = "name"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 1, index = 0 }
name = "index_shipping_methods_by_id"
on = 1
columns = [{ column = { table = 1, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 1, index = 1 }
name = "index_shipping_methods_by_stripe_id"
on = 1
columns = [{ column = { table = 1, index = 1 }, op = "Eq", scope = "Partition" }]
unique = true

[[schema.tables]]
id = 2
name = "orders"
primary_key = { columns = [{ table = 2, index = 0 }], index = { table = 2, index = 0 } }

[[schema.tables.columns]]
id = { table = 2, index = 0 }
name = "id"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 2, index = 1 }
name = "created_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 2, index = 2 }
name = "updated_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 2, index = 3 }
name = "amount"
ty = "F64"
storage_ty = { Float = 8 }

[[schema.tables.columns]]
id = { table = 2, index = 4 }
name = "status"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.columns]]
id = { table = 2, index = 5 }
name = "tracking_id"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 2, index = 6 }
name = "customer_id"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.columns]]
id = { table = 2, index = 7 }
name = "shipping_method_id"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.indices]]
id = { table = 2, index = 0 }
name = "index_orders_by_id"
on = 2
columns = [{ column = { table = 2, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 2, index = 1 }
name = "index_orders_by_customer_id"
on = 2
columns = [{ column = { table = 2, index = 6 }, op = "Eq", scope = "Partition" }]

[[schema.tables.indices]]
id = { table = 2, index = 2 }
name = "index_orders_by_shipping_method_id"
on = 2
columns = [{ column = { table = 2, index = 7 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 3
name = "customers"
primary_key = { columns = [{ table = 3, index = 0 }], index = { table = 3, index = 0 } }

[[schema.tables.columns]]
id = { table = 3, index = 0 }
name = "id"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 3, index = 1 }
name = "created_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 3, index = 2 }
name = "updated_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 3, index = 3 }
name = "name"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 3, index = 4 }
name = "email"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 3, index = 0 }
name = "index_customers_by_id"
on = 3
columns = [{ column = { table = 3, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 3, index = 1 }
name = "index_customers_by_email"
on = 3
columns = [{ column = { table = 3, index = 4 }, op = "Eq", scope = "Partition" }]
unique = true

[[schema.tables]]
id = 4
name = "order_products"
primary_key = { columns = [{ table = 4, index = 0 }], index = { table = 4, index = 0 } }

[[schema.tables.columns]]
id = { table = 4, index = 0 }
name = "id"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 4, index = 1 }
name = "order_id"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.columns]]
id = { table = 4, index = 2 }
name = "product_id"
ty = "U64"
storage_ty = { UnsignedInteger = 8 }

[[schema.tables.indices]]
id = { table = 4, index = 0 }
name = "index_order_products_by_id"
on = 4
columns = [{ column = { table = 4, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 4, index = 1 }
name = "index_order_products_by_order_id"
on = 4
columns = [{ column = { table = 4, index = 1 }, op = "Eq", scope = "Partition" }]

[[schema.tables.indices]]
id = { table = 4, index = 2 }
name = "index_order_products_by_product_id"
on = 4
columns = [{ column = { table = 4, index = 2 }, op = "Eq", scope = "Partition" }]
